# .github/workflows/reusable-workflow.yml
name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name"
        required: true
        type: string
        default: 'main'

jobs:
  job-for-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch_name }}
        
    - name: Run script based on branch
      run: |
        if [[ "${{ inputs.branch_name}}" == "main" ]]; then
          echo "Running job for the main branch"
         elif [[ "${{ inputs.branch_name}}" == 'dev' ]]; then
          echo "Running job for the dev branch"
         else
           echo "other branch"
         fi  
