# .github/workflows/reusable-workflow.yml
name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch name"
        required: true
        type: string
     

jobs:
  job-for-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        
    - name: Run script based on branch
      run: |
        if [[ "${{ inputs.branch}}" == "main" ]]; then
          echo "Running job for the main branch"
         elif [[ "${{ inputs.branch}}" == 'dev' ]]; then
          echo "Running job for the dev branch"
         else
           echo "other branch"
         fi  
