# .github/workflows/main.yml
name: "Main Workflow"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
        
jobs:
  call-reusable-workflow:
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        name: "Welcome Github"
