# .github/workflows/main.yml
name: "Main Workflow"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
        
jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v2
      
      #- name: Determine branch name
      #  run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      #  shell: bash
      
      - name: call reusable workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          #name: ${{ env.branch_name }}
          name: "Welcome Github"
