# .github/workflows/main.yml
name: "Main Workflow"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Determine branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Call reusable workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          branch: ${{ env.branch_name }}
