# .github/workflows/reusable-workflow.yml
name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      name:
        description: "Branch name"
        required: true
        type: string
        default: 'main'

jobs:
  job-for-main:
    runs-on: ubuntu-latest
    if: ${{ inputs.name == 'main' }}
    steps:
      - name: run main branch
        run: echo "execute main branch code"
  job-for-dev:
    runs-on: ubuntu-latest
    if: ${{ inputs.name == 'dev }}
    steps:
      - name: run dev branch
        run: echo "execute dev branch code"
