# .github/workflows/reusable-workflow.yml
name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      name:
        description: "Branch name"
        required: true
        type: string
        default: 'main'

jobs:
  #greet:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: run greet
   #     run: echo ${{ inputs.name }} 
  job-for-main:
    runs-on: ubuntu-latest
    #if: ${{ inputs.name == "main" }}
    steps:
      - name: run main branch
        run: echo "Hello, ${{ inputs.name}}!"
 # job-for-dev:
 #   runs-on: ubuntu-latest
 #   if: ${{ inputs.name == "dev" }}
 #   steps:
 #     - name: run dev branch
 #       run: echo "Hello, ${{ inputs.name}}!"
